// Code generated by https://github.com/jishaocong0910/cozy-orm. YOU CAN EDIT FOR MORE.

package {{.PkgName}}

import orm "github.com/jishaocong0910/cozy-orm"

var CountDao = _CountDao{orm.CountDaoBuilder().Build()}

type _CountDao struct {
	*orm.CountDao
}
