// Code generated by https://github.com/jishaocong0910/cozy-orm. YOU CAN EDIT FOR MORE.

package {{.PkgName}}

import (
	"{{.EntityPkgPath}}"
)

var {{.DaoName}} = _{{.DaoName}}{BaseDaoBuilder[entity.{{.EntityName}}]()
{{- if ne .LogicalDelTplParam nil}}.
    LogicalDelCfg(LogicalDelCfg{Column: "{{.LogicalDelTplParam.Column}}"{{if ne .LogicalDelTplParam.IdColumn ""}}, IdColumn: "{{.LogicalDelTplParam.IdColumn}}"{{end}}, QueryValue: {{.LogicalDelTplParam.QueryValue}}})
{{- end -}}
.Build()}

type _{{.DaoName}} struct {
	*baseDao[entity.{{.EntityName}}]
}

