// Code generated by https://github.com/jishaocong0910/cozy-orm. YOU CAN EDIT FOR MORE.

package entity

{{- if gt (len .Imports) 0}}
import (
    {{- range $i := .Imports}}
    {{$i}}
    {{- end}}
)
{{- end}}

// {{.EntityName}}{{if ne .Comment "" }} {{.Comment}}{{end}}
type {{.EntityName}} struct {
{{- range $f := .Fields}}
	{{- if ne $f.Comment ""}}
	// {{$f.Comment}}
	{{- end}}
	{{- if or $f.IsNotNull $f.HasDefaultValue}}
	//{{if $f.IsNotNull}} not_null{{end}}{{if $f.HasDefaultValue}} has_default_value{{end}}
	{{- end}}
	{{- if not $f.Valid}}
	// cozy-orm cannot solve this type!
	{{- end}}
	{{$f.FieldName}} {{$f.FieldType}} {{if not $f.Valid}}`orm:"skip"`{{else}}`orm:"column={{$f.Column}}{{if $f.IsAutoIncrement}};auto{{end}}{{if gt $f.AutoIncrementStep 0}}={{$f.AutoIncrementStep}}{{end}}"`{{end}}
{{- end}}
}

func ({{.EntityName}}) Table() string {
	return "{{.Table}}"
}

