// Code generated by https://github.com/jishaocong0910/cozy-orm. FOR Oracle. DO NOT EDIT.

package {{.PkgName}}

import (
	"context"
	"database/sql"
	"errors"
	"reflect"
	"strconv"
	"unsafe"

	orm "github.com/jishaocong0910/cozy-orm"
	e "github.com/jishaocong0910/enum"
)

type get[T orm.Entity] struct {
	dao         *baseDao[T]
	ctx         context.Context
	must        bool
	sqlLogLevel orm.LogLevel
	desc        string
	sel         []string
	cg          *CondGroup
	deletion    bool
	orderBy     *OrderBy
	forUpdate   bool
	checkOne    bool
}

// The context
func (g *get[T]) Ctx(ctx context.Context) *get[T] { // coverage-ignore
	g.ctx = ctx
	return g
}

// If true, panic when error occurs, otherwise, return error.
func (g *get[T]) Must(must bool) *get[T] { // coverage-ignore
	g.must = must
	return g
}

// Specify the SQL log level.
func (g *get[T]) SqlLogLevel(logLevel orm.LogLevel) *get[T] { // coverage-ignore
	g.sqlLogLevel = logLevel
	return g
}

// Describe the SQL in the log.
func (g *get[T]) Desc(desc string) *get[T] { // coverage-ignore
	g.desc = desc
	return g
}

// Specify the columns which in the select column list, default is all columns.
func (g *get[T]) Select(sel ...string) *get[T] {
	g.sel = mapColumns(g.dao.fieldNameToColumn, sel)
	return g
}

// Conditions of the WHERE clause, create by function And, Or and Not.
func (g *get[T]) Condition(cg *CondGroup) *get[T] {
	g.cg = cg
	return g
}

// If true, the conditions do not automatically filter out deleted rows in logical delete mode.
func (g *get[T]) Deletion(deletion bool) *get[T] {
	g.deletion = deletion
	return g
}

// ORDER BY clause, create by function Order.
func (g *get[T]) Order(orderBy *OrderBy) *get[T] {
	g.orderBy = orderBy
	return g
}

// FOR UPDATE clause
func (g *get[T]) ForUpdate(forUpdate bool) *get[T] {
	g.forUpdate = forUpdate
	return g
}

// Must return one row, default is false.
func (g *get[T]) CheckOne(checkOne bool) *get[T] {
	g.checkOne = checkOne
	return g
}

// Execute SQL
func (g *get[T]) Do() (*T, error) {
	ls, err := g.dao.List().Ctx(g.ctx).Must(g.must).SqlLogLevel(g.sqlLogLevel).Desc(g.desc).
		Select(g.sel...).Condition(g.cg).Deletion(g.deletion).OrderBy(g.orderBy).
		ForUpdate(g.forUpdate).Do()
	if len(ls) == 0 { // coverage-ignore
		return nil, err
	}
	if g.checkOne && len(ls) > 1 {
		err = errors.New("return more than one row")
		if g.must { // coverage-ignore
			panic(err)
		}
	}
	return ls[0], err
}

type list[T orm.Entity] struct {
	dao         *baseDao[T]
	ctx         context.Context
	must        bool
	sqlLogLevel orm.LogLevel
	desc        string
	sel         []string
	cg          *CondGroup
	deletion    bool
	orderBy     *OrderBy
	paging      *Paging
	forUpdate   bool
}

// The context
func (l *list[T]) Ctx(ctx context.Context) *list[T] {
	l.ctx = ctx
	return l
}

// If true, panic when error occurs, otherwise, return error.
func (l *list[T]) Must(must bool) *list[T] {
	l.must = must
	return l
}

// Specify the SQL log level.
func (l *list[T]) SqlLogLevel(logLevel orm.LogLevel) *list[T] {
	l.sqlLogLevel = logLevel
	return l
}

// Describe the SQL in the log.
func (l *list[T]) Desc(desc string) *list[T] {
	l.desc = desc
	return l
}

// Specify the columns which in the select column list, default is all columns.
func (l *list[T]) Select(sel ...string) *list[T] {
	l.sel = mapColumns(l.dao.fieldNameToColumn, sel)
	return l
}

// Conditions of the WHERE clause, create by function And, Or and Not.
func (l *list[T]) Condition(cg *CondGroup) *list[T] {
	l.cg = cg
	return l
}

// If true, the conditions do not automatically filter out deleted rows in logical delete mode.
func (l *list[T]) Deletion(deletion bool) *list[T] {
	l.deletion = deletion
	return l
}

// ORDER BY clause, create by function Order.
func (l *list[T]) OrderBy(orderBy *OrderBy) *list[T] {
	l.orderBy = orderBy
	return l
}

// Paging query, create by function Page.
func (l *list[T]) Page(paging *Paging) *list[T] {
	l.paging = paging
	return l
}

// FOR UPDATE clause
func (l *list[T]) ForUpdate(forUpdate bool) *list[T] {
	l.forUpdate = forUpdate
	return l
}

// Execute SQL
func (l *list[T]) Do() ([]*T, error) {
	_, list, err := l.dao.Query().Ctx(l.ctx).Must(l.must).SqlLogLevel(l.sqlLogLevel).Desc(l.desc).BuildSql(func(b *orm.SqlBuilder[T]) {
		b.Write("SELECT ").WriteColumns(l.sel...).Write(" FROM ").WriteTable()
		cg := l.dao.determineCond(l.cg, l.deletion)
		if cg.notEmpty() {
			b.Write(" WHERE ")
			cg.write(l.dao.fieldNameToColumn, b.PlainSqlBuilder)
		}
		if l.orderBy != nil {
			l.orderBy.write(l.dao.fieldNameToColumn, b.PlainSqlBuilder)
		}
		if l.paging != nil {
			if l.paging.offset > 0 {
				b.Write(" OFFSET ")
				b.Write(strconv.FormatInt(int64(l.paging.offset), 10))
			}
			b.Write(" FETCH NEXT ")
			b.Write(strconv.FormatInt(int64(l.paging.pageSize), 10))
			b.Write(" ROWS ONLY")
		}
		b.WriteIf(" FOR UPDATE", l.forUpdate)
	}).Do()
	return list, err
}

type insert[T orm.Entity] struct {
	dao         *baseDao[T]
	ctx         context.Context
	must        bool
	sqlLogLevel orm.LogLevel
	desc        string
	entity      *T
	nullable    []string
	all         bool
	ignore      []string
}

// The context
func (i *insert[T]) Ctx(ctx context.Context) *insert[T] { // coverage-ignore
	i.ctx = ctx
	return i
}

// If true, panic when error occurs, otherwise, return error.
func (i *insert[T]) Must(must bool) *insert[T] { // coverage-ignore
	i.must = must
	return i
}

// Specify the SQL log level.
func (i *insert[T]) SqlLogLevel(logLevel orm.LogLevel) *insert[T] { // coverage-ignore
	i.sqlLogLevel = logLevel
	return i
}

// Describe the SQL in the log.
func (i *insert[T]) Desc(desc string) *insert[T] { // coverage-ignore
	i.desc = desc
	return i
}

// The non-nil fields will be saved, except the field which has the auto tag. Auto generated keys will be set to this entity.
func (i *insert[T]) Entity(entity *T) *insert[T] {
	i.entity = entity
	return i
}

// Specify the columns that mapped field is nil in the entity set to null. Work only All is false.
func (i *insert[T]) Nullable(nullable ...string) *insert[T] {
	i.nullable = mapColumns(i.dao.fieldNameToColumn, nullable)
	return i
}

// If true, all fields will be saved (except the auto generated columns), otherwise, save non-nil fields.
func (i *insert[T]) All(all bool) *insert[T] {
	i.all = all
	return i
}

// Ignore fields. Work only All is true.
func (i *insert[T]) Ignore(ignore ...string) *insert[T] {
	i.ignore = mapColumns(i.dao.fieldNameToColumn, ignore)
	return i
}

func (i *insert[T]) Do() (int64, error) {
	return i.dao.InsertBatch().Ctx(i.ctx).Must(i.must).SqlLogLevel(i.sqlLogLevel).Desc(i.desc).Entities(i.entity).
		Nullable(i.nullable...).All(i.all).Ignore(i.ignore...).Do()
}

type insertBatch[T orm.Entity] struct {
	dao         *baseDao[T]
	ctx         context.Context
	must        bool
	sqlLogLevel orm.LogLevel
	desc        string
	entities    []*T
	nullable    []string
	all         bool
	ignore      []string
}

// The context
func (ib *insertBatch[T]) Ctx(ctx context.Context) *insertBatch[T] {
	ib.ctx = ctx
	return ib
}

// If true, panic when error occurs, otherwise, return error.
func (ib *insertBatch[T]) Must(must bool) *insertBatch[T] {
	ib.must = must
	return ib
}

// Specify the SQL log level.
func (ib *insertBatch[T]) SqlLogLevel(logLevel orm.LogLevel) *insertBatch[T] {
	ib.sqlLogLevel = logLevel
	return ib
}

// Describe the SQL in the log.
func (ib *insertBatch[T]) Desc(desc string) *insertBatch[T] {
	ib.desc = desc
	return ib
}

// Each element corresponds to a record to be saved. Only the non-nil fields will be saved, except the field which has the auto tag.
// Auto generated keys will be set to these entities.
//
// Please note: the non-nil fields will be taken from the first entity.
func (ib *insertBatch[T]) Entities(entities ...*T) *insertBatch[T] {
	ib.entities = entities
	return ib
}

// Specify the columns that mapped field is nil in the first entity set to null. Work only All is false.
func (ib *insertBatch[T]) Nullable(nullable ...string) *insertBatch[T] {
	ib.nullable = mapColumns(ib.dao.fieldNameToColumn, nullable)
	return ib
}

// If true, all fields will be saved, otherwise, save non-nil fields.
func (ib *insertBatch[T]) All(all bool) *insertBatch[T] {
	ib.all = all
	return ib
}

// Ignore fields. Work only All is true.
func (ib *insertBatch[T]) Ignore(ignore ...string) *insertBatch[T] {
	ib.ignore = mapColumns(ib.dao.fieldNameToColumn, ignore)
	return ib
}

func (ib *insertBatch[T]) Do() (int64, error) {
	return ib.dao.Exec().Ctx(ib.ctx).Must(ib.must).SqlLogLevel(ib.sqlLogLevel).Desc(ib.desc).Entities(ib.entities...).
		BuildSql(func(b *orm.SqlBuilder[T]) {
			var columns []string
			if ib.all {
				columns = b.Columns(ib.ignore)
			} else if len(ib.entities) > 0 {
				columns = b.AssignedColumns(ib.entities[0], ib.nullable, nil)
			}

			b.Write("INSERT INTO ").WriteTable()
			b.Repeat(len(columns), b.SepFix("(", ", ", ")", false), nil, func(_, i int) {
				b.Write(columns[i])
			})

			b.Write(" VALUES ")
			b.EachEntity(b.Sep(", "), func(_ int, entity *T) {
				b.EachColumn(entity, b.SepFix("(", ", ", ")", false), func(_ int, column string, value any) {
					if value != nil {
						b.Write(b.Ph(":"), value)
					} else {
						b.Write("NULL")
					}
				}, columns...)
			})
		}).Do()
}

type update[T orm.Entity] struct {
	dao         *baseDao[T]
	ctx         context.Context
	must        bool
	sqlLogLevel orm.LogLevel
	desc        string
	entity      *T
	nullable    []string
	all         bool
	ignore      []string
	where       []string
	cg          *CondGroup
	deletion    bool
}

// The context
func (u *update[T]) Ctx(ctx context.Context) *update[T] { // coverage-ignore
	u.ctx = ctx
	return u
}

// If true, panic when error occurs, otherwise, return error.
func (u *update[T]) Must(must bool) *update[T] { // coverage-ignore
	u.must = must
	return u
}

// Specify the SQL log level.
func (u *update[T]) SqlLogLevel(logLevel orm.LogLevel) *update[T] { // coverage-ignore
	u.sqlLogLevel = logLevel
	return u
}

// Describe the SQL in the log.
func (u *update[T]) Desc(desc string) *update[T] { // coverage-ignore
	u.desc = desc
	return u
}

// The non-nil fields will be updated.
func (u *update[T]) Entity(entity *T) *update[T] {
	u.entity = entity
	return u
}

// Specify the columns that mapped field is nil in the entity set to null. Work only All is false.
func (u *update[T]) Nullable(nullable ...string) *update[T] {
	u.nullable = mapColumns(u.dao.fieldNameToColumn, nullable)
	return u
}

// If true, all fields will be updated, otherwise, update non-nil fields.
func (u *update[T]) All(all bool) *update[T] {
	u.all = all
	return u
}

// Ignore fields. Work only All is true.
func (u *update[T]) Ignore(ignore ...string) *update[T] {
	u.ignore = mapColumns(u.dao.fieldNameToColumn, ignore)
	return u
}

// Specify the fields used as conditions rather than to be updated.
func (u *update[T]) Where(where ...string) *update[T] {
	u.where = mapColumns(u.dao.fieldNameToColumn, where)
	return u
}

// Conditions of the WHERE clause, create by function And, Or and Not.
func (u *update[T]) Condition(cg *CondGroup) *update[T] {
	u.cg = cg
	return u
}

// If true, the conditions do not automatically filter out deleted rows in logical delete mode.
func (u *update[T]) Deletion(deletion bool) *update[T] {
	u.deletion = deletion
	return u
}

// Execute SQL
func (u *update[T]) Do() (int64, error) {
	return u.dao.Exec().Ctx(u.ctx).Must(u.must).SqlLogLevel(u.sqlLogLevel).Desc(u.desc).Entities(u.entity).BuildSql(func(b *orm.SqlBuilder[T]) {
		var columns []string
		if u.all {
			columns = b.Columns(mergeColumns(u.ignore, u.where))
		} else if u.entity != nil {
			columns = b.AssignedColumns(u.entity, u.nullable, u.where)
		}

		b.Write("UPDATE ").WriteTable().Write(" SET ")
		b.EachColumn(b.Entity(), b.Sep(", "), func(_ int, column string, value any) {
			b.Write(column).Write(" = ")
			if value != nil {
				b.Write(b.Ph(":"), value)
			} else {
				b.Write("NULL")
			}
		}, columns...)

		cg := And()
		if len(u.where) > 0 {
			b.EachColumn(b.Entity(), nil, func(_ int, column string, value any) {
				if value == nil {
					cg.IsNull(column)
				} else {
					cg.Eq(column, value)
				}
			}, u.where...)
		}
		cg.add(u.cg)
		cg = u.dao.determineCond(cg, u.deletion)
		if cg.notEmpty() {
			b.Write(" WHERE ")
			cg.write(u.dao.fieldNameToColumn, b.PlainSqlBuilder)
		}
	}).Do()
}

type updateBatch[T orm.Entity] struct {
	dao         *baseDao[T]
	ctx         context.Context
	must        bool
	sqlLogLevel orm.LogLevel
	desc        string
	entities    []*T
	nullable    []string
	all         bool
	ignore      []string
	where       string
	cg          *CondGroup
	deletion    bool
}

// The context
func (u *updateBatch[T]) Ctx(ctx context.Context) *updateBatch[T] { // coverage-ignore
	u.ctx = ctx
	return u
}

// If true, panic when error occurs, otherwise, return error.
func (u *updateBatch[T]) Must(must bool) *updateBatch[T] { // coverage-ignore
	u.must = must
	return u
}

// Specify the SQL log level.
func (u *updateBatch[T]) SqlLogLevel(logLevel orm.LogLevel) *updateBatch[T] { // coverage-ignore
	u.sqlLogLevel = logLevel
	return u
}

// Describe the SQL in the log.
func (u *updateBatch[T]) Desc(desc string) *updateBatch[T] { // coverage-ignore
	u.desc = desc
	return u
}

// Each element corresponds to a record to be saved, only the non-nil fields will be saved.
//
// Please note: the non-nil fields will take from the first entity.
func (u *updateBatch[T]) Entities(entities ...*T) *updateBatch[T] {
	u.entities = entities
	return u
}

// Specify the columns that mapped field is nil in the entity set to null. Work only All is false.
func (u *updateBatch[T]) Nullable(nullable ...string) *updateBatch[T] {
	u.nullable = mapColumns(u.dao.fieldNameToColumn, nullable)
	return u
}

// If true, all fields will be updated, otherwise, update non-nil fields.
func (u *updateBatch[T]) All(all bool) *updateBatch[T] {
	u.all = all
	return u
}

// Ignore fields. Work only All is true.
func (u *updateBatch[T]) Ignore(ignore ...string) *updateBatch[T] {
	u.ignore = mapColumns(u.dao.fieldNameToColumn, ignore)
	return u
}

// Specify the column which is on the CASE column WHEN ... clause.
func (u *updateBatch[T]) Where(where string) *updateBatch[T] {
	u.where = mapColumn(u.dao.fieldNameToColumn, where)
	return u
}

// Conditions of the WHERE clause, create by function And, Or and Not.
func (u *updateBatch[T]) Condition(cg *CondGroup) *updateBatch[T] {
	u.cg = cg
	return u
}

// If true, the conditions do not automatically filter out deleted rows in logical delete mode.
func (u *updateBatch[T]) Deletion(deletion bool) *updateBatch[T] {
	u.deletion = deletion
	return u
}

// Execute SQL
func (u *updateBatch[T]) Do() (int64, error) {
	return u.dao.Exec().Ctx(u.ctx).Must(u.must).SqlLogLevel(u.sqlLogLevel).Desc(u.desc).Entities(u.entities...).BuildSql(func(b *orm.SqlBuilder[T]) {
		var columns []string
		if u.all {
			columns = b.Columns(mergeColumns(u.ignore, []string{u.where}))
		} else if len(u.entities) > 0 {
			columns = b.AssignedColumns(u.entities[0], u.nullable, []string{u.where})
		}

		b.Write("UPDATE ").WriteTable().Write(" SET ")
		b.EachColumn(b.Entity(), b.Sep(", "), func(_ int, column string, value any) {
			b.Write(column).Write(" = CASE ").Write(u.where)
			b.EachEntity(nil, func(_ int, entity *T) {
				b.Write(" WHEN ").Write(b.Ph(":"), b.ColumnValue(entity, u.where)).Write(" THEN ")
				if value != nil {
					b.Write(b.Ph(":"), b.ColumnValue(entity, column))
				} else {
					b.Write("NULL")
				}
			})
			b.Write(" END")
		}, columns...)

		b.Write(" WHERE ")
		cg := And()
		inValues := make([]any, 0, len(u.entities))
		b.EachEntity(nil, func(_ int, entity *T) {
			inValues = append(inValues, b.ColumnValue(entity, u.where))
		})
		cg.In(u.where, InArgs(inValues...))
		cg.add(u.cg)
		cg = u.dao.determineCond(cg, u.deletion)
		cg.write(u.dao.fieldNameToColumn, b.PlainSqlBuilder)
	}).Do()
}

type delete[T orm.Entity] struct {
	dao         *baseDao[T]
	ctx         context.Context
	must        bool
	sqlLogLevel orm.LogLevel
	desc        string
	cg          *CondGroup
}

// The context
func (d *delete[T]) Ctx(ctx context.Context) *delete[T] { // coverage-ignore
	d.ctx = ctx
	return d
}

// If true, panic when error occurs, otherwise, return error.
func (d *delete[T]) Must(must bool) *delete[T] { // coverage-ignore
	d.must = must
	return d
}

// Specify the SQL log level.
func (d *delete[T]) SqlLogLevel(logLevel orm.LogLevel) *delete[T] { // coverage-ignore
	d.sqlLogLevel = logLevel
	return d
}

// Describe the SQL in the log.
func (d *delete[T]) Desc(desc string) *delete[T] { // coverage-ignore
	d.desc = desc
	return d
}

// Conditions of the WHERE clause, create by function And, Or and Not.
func (d *delete[T]) Condition(cg *CondGroup) *delete[T] {
	d.cg = cg
	return d
}

// Execute SQL
func (d *delete[T]) Do() (int64, error) {
	return d.dao.Exec().Ctx(d.ctx).Must(d.must).SqlLogLevel(d.sqlLogLevel).Desc(d.desc).BuildSql(func(b *orm.SqlBuilder[T]) {
		b.Write("DELETE FROM ").WriteTable()
		if d.cg.notEmpty() {
			b.Write(" WHERE ")
			d.cg.write(d.dao.fieldNameToColumn, b.PlainSqlBuilder)
		}
	}).Do()
}

type logicalDelete[T orm.Entity] struct {
	dao         *baseDao[T]
	ctx         context.Context
	must        bool
	sqlLogLevel orm.LogLevel
	desc        string
	cg          *CondGroup
}

// The context
func (l *logicalDelete[T]) Ctx(ctx context.Context) *logicalDelete[T] { // coverage-ignore
	l.ctx = ctx
	return l
}

// If true, panic when error occurs, otherwise, return error.
func (l *logicalDelete[T]) Must(must bool) *logicalDelete[T] { // coverage-ignore
	l.must = must
	return l
}

// Specify the SQL log level.
func (l *logicalDelete[T]) SqlLogLevel(logLevel orm.LogLevel) *logicalDelete[T] { // coverage-ignore
	l.sqlLogLevel = logLevel
	return l
}

// Describe the SQL in the log.
func (l *logicalDelete[T]) Desc(desc string) *logicalDelete[T] { // coverage-ignore
	l.desc = desc
	return l
}

// Conditions of the WHERE clause, create by function And, Or and Not.
func (l *logicalDelete[T]) Condition(cg *CondGroup) *logicalDelete[T] {
	l.cg = cg
	return l
}

// Execute SQL
func (l *logicalDelete[T]) Do() (int64, error) {
	return l.dao.Exec().Ctx(l.ctx).Must(l.must).SqlLogLevel(l.sqlLogLevel).Desc(l.desc).BuildSql(func(b *orm.SqlBuilder[T]) {
		if l.dao.logicalDelCfg == nil { // coverage-ignore
			b.SetError(errors.New("logical deletion is not supported"))
			return
		}
		b.Write("UPDATE ").WriteTable().Write(" SET ").Write(l.dao.logicalDelCfg.Column).Write(" = ")
		if l.dao.logicalDelCfg.IdColumn != "" {
			b.Write(l.dao.logicalDelCfg.IdColumn)
		} else {
			b.Write("NULL")
		}
		b.Write(" WHERE ")
		cg := l.dao.determineCond(l.cg, false)
		cg.write(l.dao.fieldNameToColumn, b.PlainSqlBuilder)
	}).Do()
}

type count[T orm.Entity] struct {
	dao         *baseDao[T]
	ctx         context.Context
	must        bool
	sqlLogLevel orm.LogLevel
	desc        string
	cg          *CondGroup
	deletion    bool
}

// The context
func (c *count[T]) Ctx(ctx context.Context) *count[T] { // coverage-ignore
	c.ctx = ctx
	return c
}

// If true, panic when error occurs, otherwise, return error.
func (c *count[T]) Must(must bool) *count[T] { // coverage-ignore
	c.must = must
	return c
}

// Specify the SQL log level.
func (c *count[T]) SqlLogLevel(logLevel orm.LogLevel) *count[T] { // coverage-ignore
	c.sqlLogLevel = logLevel
	return c
}

// Describe the SQL in the log.
func (c *count[T]) Desc(desc string) *count[T] { // coverage-ignore
	c.desc = desc
	return c
}

// Conditions of the WHERE clause, create by function And, Or and Not.
func (c *count[T]) Condition(cg *CondGroup) *count[T] {
	c.cg = cg
	return c
}

// If true, the conditions do not automatically filter out deleted rows in logical delete mode.
func (c *count[T]) Deletion(deletion bool) *count[T] {
	c.deletion = deletion
	return c
}

// Execute SQL
func (c *count[T]) Do() (*orm.Count, error) {
	return c.dao.Dao.Count().Ctx(c.ctx).Must(c.must).SqlLogLevel(c.sqlLogLevel).Desc(c.desc).BuildSql(func(b *orm.SqlBuilder[T]) {
		b.Write("SELECT COUNT(*) FROM ").WriteTable()
		cg := c.dao.determineCond(c.cg, c.deletion)
		if cg.notEmpty() {
			b.Write(" WHERE ")
			cg.write(c.dao.fieldNameToColumn, b.PlainSqlBuilder)
		}
	}).Do()
}

type baseDao[T orm.Entity] struct {
	*orm.Dao[T]
	logicalDelCfg     *LogicalDelCfg
	fieldNameToColumn map[string]string
}

func (d *baseDao[T]) Get() *get[T] {
	return &get[T]{dao: d}
}

func (d *baseDao[T]) List() *list[T] {
	return &list[T]{dao: d}
}

func (d *baseDao[T]) Insert() *insert[T] {
	return &insert[T]{dao: d}
}

func (d *baseDao[T]) InsertBatch() *insertBatch[T] {
	return &insertBatch[T]{dao: d}
}

func (d *baseDao[T]) Update() *update[T] {
	return &update[T]{dao: d}
}

func (d *baseDao[T]) UpdateBatch() *updateBatch[T] {
	return &updateBatch[T]{dao: d}
}

func (d *baseDao[T]) Delete() *delete[T] {
	return &delete[T]{dao: d}
}

func (d *baseDao[T]) LogicalDelete() *logicalDelete[T] {
	return &logicalDelete[T]{dao: d}
}

func (d *baseDao[T]) Count() *count[T] {
	return &count[T]{dao: d}
}

func (d *baseDao[T]) determineCond(cg *CondGroup, deletion bool) *CondGroup {
	if deletion || d.logicalDelCfg == nil {
		return cg
	}
	return And().Add(cg).Add(And().Eq(d.logicalDelCfg.Column, d.logicalDelCfg.QueryValue))
}

type baseDaoBuilder[T orm.Entity] struct {
	baseDao      *baseDao[T]
	db           *sql.DB
	columnMapper *orm.NameMapper
}

func (b *baseDaoBuilder[T]) DB(db *sql.DB) *baseDaoBuilder[T] { // coverage-ignore
	b.db = db
	return b
}

func (b *baseDaoBuilder[T]) ColumnMapper(columnMapper *orm.NameMapper) *baseDaoBuilder[T] { // coverage-ignore
	b.columnMapper = columnMapper
	return b
}

func (b *baseDaoBuilder[T]) LogicalDelCfg(logicalDelCfg *LogicalDelCfg) *baseDaoBuilder[T] {
	b.baseDao.logicalDelCfg = logicalDelCfg
	return b
}

func (b *baseDaoBuilder[T]) Build() *baseDao[T] {
	dao := orm.DaoBuilder[T]().DB(b.db).ColumnMapper(b.columnMapper).Build()
	b.baseDao.Dao = dao
	b.baseDao.fieldNameToColumn = *(*map[string]string)(unsafe.Pointer(reflect.ValueOf(dao).Elem().FieldByName("fieldNameToColumn").UnsafeAddr()))
	return b.baseDao
}

func BaseDaoBuilder[T orm.Entity]() *baseDaoBuilder[T] {
	return &baseDaoBuilder[T]{baseDao: &baseDao[T]{}}
}

type LogicalDelCfg struct {
	Column     string
	IdColumn   string
	QueryValue any
}

//=============================================================
//======================== Condition  =========================
//=============================================================

type cond interface {
	notEmpty() bool
	setNot()
	write(nameMap map[string]string, b *orm.PlainSqlBuilder)
}

type baseCond struct {
	not           bool
	parenthesized bool
}

func (bc *baseCond) notEmpty() bool {
	return true
}

func (bc *baseCond) setNot() {
	bc.not = true
}

func (bc *baseCond) doWrite(b *orm.PlainSqlBuilder, write func()) {
	if bc.not {
		b.Write("NOT ")
	}
	if bc.parenthesized {
		b.Write("(")
	}
	write()
	if bc.parenthesized {
		b.Write(")")
	}
}

type not struct{}

func (n not) And() *CondGroup {
	return &CondGroup{baseCond: baseCond{not: true}, or: false}
}

func (n not) Or() *CondGroup {
	return &CondGroup{baseCond: baseCond{not: true}, or: true}
}

type CondGroup struct {
	baseCond
	nextNot bool
	or      bool
	cs      []cond
}

func (cg *CondGroup) notEmpty() bool {
	if cg == nil {
		return false
	}
	return len(cg.cs) > 0
}

func (cg *CondGroup) write(nameMap map[string]string, b *orm.PlainSqlBuilder) {
	cg.doWrite(b, func() {
		for i, c := range cg.cs {
			if i != 0 {
				if cg.or {
					b.Write(" OR ")
				} else {
					b.Write(" AND ")
				}
			}
			c.write(nameMap, b)
		}
	})
}

func (cg *CondGroup) add(other cond) *CondGroup {
	if other != nil && other.notEmpty() {
		if cg.nextNot {
			other.setNot()
			cg.nextNot = false
			if g, ok := other.(*CondGroup); ok {
				if len(g.cs) > 1 {
					g.parenthesized = true
				}
			}
		}
		if len(cg.cs) == 1 {
			if cg.not {
				cg.parenthesized = true
			}
			first := cg.cs[0]
			if g, ok := first.(*CondGroup); ok {
				if g.or && len(g.cs) > 1 {
					g.parenthesized = true
				}
			}
		}
		if len(cg.cs) > 0 {
			if g, ok := other.(*CondGroup); ok {
				if g.or && len(g.cs) > 1 {
					g.parenthesized = true
				}
			}
		}
		cg.cs = append(cg.cs, other)
	}
	return cg
}

func (cg *CondGroup) ToStrArgs(nameMap map[string]string) (string, []any) {
	b := &orm.PlainSqlBuilder{}
	cg.write(nameMap, b)
	return b.Sql(), b.Args()
}

func (cg *CondGroup) Not() *CondGroup {
	cg.nextNot = true
	return cg
}

func (cg *CondGroup) Add(other *CondGroup) *CondGroup {
	return cg.add(other)
}

func (cg *CondGroup) Plain(sql string, args ...any) *CondGroup {
	return cg.add(&condPlain{sql: sql, args: args})
}

func (cg *CondGroup) Eq(column string, arg any, opts ...CondOpt) *CondGroup {
	opt := cg.getOpt(opts...)
	if opt.ifPresent && arg == nil {
		return cg
	}
	if opt.ifPredicate != nil {
		if !opt.ifPredicate() {
			return cg
		}
	}
	return cg.add(&condBinOp{column: column, op: "=", arg: arg})
}

func (cg *CondGroup) Ne(column string, arg any, opts ...CondOpt) *CondGroup {
	opt := cg.getOpt(opts...)
	if opt.ifPresent && arg == nil {
		return cg
	}
	if opt.ifPredicate != nil {
		if !opt.ifPredicate() {
			return cg
		}
	}
	return cg.add(&condBinOp{column: column, op: "<>", arg: arg})
}

func (cg *CondGroup) Gt(column string, arg any, opts ...CondOpt) *CondGroup {
	opt := cg.getOpt(opts...)
	if opt.ifPresent && arg == nil {
		return cg
	}
	if opt.ifPredicate != nil {
		if !opt.ifPredicate() {
			return cg
		}
	}
	return cg.add(&condBinOp{column: column, op: ">", arg: arg})
}

func (cg *CondGroup) Lt(column string, arg any, opts ...CondOpt) *CondGroup {
	opt := cg.getOpt(opts...)
	if opt.ifPresent && arg == nil {
		return cg
	}
	if opt.ifPredicate != nil {
		if !opt.ifPredicate() {
			return cg
		}
	}
	return cg.add(&condBinOp{column: column, op: "<", arg: arg})
}

func (cg *CondGroup) Ge(column string, arg any, opts ...CondOpt) *CondGroup {
	opt := cg.getOpt(opts...)
	if opt.ifPresent && arg == nil {
		return cg
	}
	if opt.ifPredicate != nil {
		if !opt.ifPredicate() {
			return cg
		}
	}
	return cg.add(&condBinOp{column: column, op: ">=", arg: arg})
}

func (cg *CondGroup) Le(column string, arg any, opts ...CondOpt) *CondGroup {
	opt := cg.getOpt(opts...)
	if opt.ifPresent && arg == nil {
		return cg
	}
	if opt.ifPredicate != nil {
		if !opt.ifPredicate() {
			return cg
		}
	}
	return cg.add(&condBinOp{column: column, op: "<=", arg: arg})
}

func (cg *CondGroup) Like(column string, arg string, opts ...CondOpt) *CondGroup {
	opt := cg.getOpt(opts...)
	if opt.ifPresent && arg == "" {
		return cg
	}
	if opt.ifPredicate != nil {
		if !opt.ifPredicate() {
			return cg
		}
	}
	return cg.add(&condBinOp{column: column, op: "LIKE", arg: "%" + arg + "%"})
}

func (cg *CondGroup) LikeLeft(column string, arg string, opts ...CondOpt) *CondGroup {
	opt := cg.getOpt(opts...)
	if opt.ifPresent && arg == "" {
		return cg
	}
	if opt.ifPredicate != nil {
		if !opt.ifPredicate() {
			return cg
		}
	}
	return cg.add(&condBinOp{column: column, op: "LIKE", arg: arg + "%"})
}

func (cg *CondGroup) LikeRight(column string, arg string, opts ...CondOpt) *CondGroup {
	opt := cg.getOpt(opts...)
	if opt.ifPresent && arg == "" {
		return cg
	}
	if opt.ifPredicate != nil {
		if !opt.ifPredicate() {
			return cg
		}
	}
	return cg.add(&condBinOp{column: column, op: "LIKE", arg: "%" + arg})
}

func (cg *CondGroup) In(column string, args inArgs, opts ...CondOpt) *CondGroup {
	opt := cg.getOpt(opts...)
	if opt.ifPresent && len(args) == 0 {
		return cg
	}
	if opt.ifPredicate != nil {
		if !opt.ifPredicate() {
			return cg
		}
	}
	return cg.add(&condIn{column: column, args: args})
}

func (cg *CondGroup) Between(column string, min, max any, opts ...CondOpt) *CondGroup {
	opt := cg.getOpt(opts...)
	if opt.ifPresent && (min == nil || max == nil) {
		return cg
	}
	if opt.ifPredicate != nil {
		if !opt.ifPredicate() {
			return cg
		}
	}
	return cg.add(&condBetween{column: column, min: min, max: max})
}

func (cg *CondGroup) IsNull(column string) *CondGroup {
	return cg.add(&condIsNull{column: column})
}

func (cg *CondGroup) IsNotNull(column string) *CondGroup {
	return cg.add(&condIsNull{column: column, notNull: true})
}

func (cg *CondGroup) getOpt(opts ...CondOpt) condOpt {
	co := condOpt{}
	for _, opt := range opts {
		opt(&co)
	}
	return co
}

type condPlain struct {
	baseCond
	sql  string
	args []any
}

func (c *condPlain) write(_ map[string]string, b *orm.PlainSqlBuilder) {
	c.doWrite(b, func() {
		b.Write(c.sql, c.args...)
	})
}

type condBinOp struct {
	baseCond
	column string
	op     string
	arg    any
}

func (c *condBinOp) write(nameMap map[string]string, b *orm.PlainSqlBuilder) {
	c.doWrite(b, func() {
		b.Write(mapColumn(nameMap, c.column))
		b.Write(" ")
		b.Write(c.op)
		b.Write(" ")
		b.Write(b.Ph(":"), c.arg)
	})
}

type condIn struct {
	baseCond
	column string
	args   []any
}

func (c *condIn) write(nameMap map[string]string, b *orm.PlainSqlBuilder) {
	c.doWrite(b, func() {
		b.Write(mapColumn(nameMap, c.column))
		b.Write(" IN(")
		for i := 0; i < len(c.args); i++ {
			if i != 0 {
				b.Write(", ")
			}
			b.Write(b.Ph(":"))
		}
		b.Write(")", c.args...)
	})
}

type condBetween struct {
	baseCond
	column   string
	min, max any
}

func (c *condBetween) write(nameMap map[string]string, b *orm.PlainSqlBuilder) {
	c.doWrite(b, func() {
		b.Write(mapColumn(nameMap, c.column))
		b.Write(" BETWEEN ")
		b.Write(b.Ph(":"))
		b.Write(" AND ")
		b.Write(b.Ph(":"), c.min, c.max)
	})
}

type condIsNull struct {
	baseCond
	notNull bool
	column  string
}

func (c *condIsNull) write(nameMap map[string]string, b *orm.PlainSqlBuilder) {
	c.doWrite(b, func() {
		b.Write(mapColumn(nameMap, c.column))
		b.Write(" IS")
		if c.notNull {
			b.Write(" NOT")
		}
		b.Write(" NULL")
	})
}

type inArgs []any

func InArgs[T any](source ...T) inArgs {
	var target inArgs
	for _, s := range source {
		target = append(target, s)
	}
	return target
}

//=============================================================
//===================== Condition Options =====================
//=============================================================

type condOpt struct {
	ifPresent   bool
	ifPredicate func() bool
}

type CondOpt func(*condOpt)

func WithIfPresent() CondOpt {
	return func(opt *condOpt) {
		opt.ifPresent = true
	}
}

func WithIfPredicate(predicate func() bool) CondOpt {
	return func(opt *condOpt) {
		opt.ifPredicate = predicate
	}
}

//=============================================================
//======================= SQL Modifier ========================
//=============================================================

type OrderBy struct {
	items []orderByItem
}

func (o *OrderBy) Asc(column string) *OrderBy {
	o.items = append(o.items, orderByItem{column: column, seq: orderBySeq_.asc})
	return o
}

func (o *OrderBy) Desc(column string) *OrderBy {
	o.items = append(o.items, orderByItem{column: column, seq: orderBySeq_.desc})
	return o
}

func (o *OrderBy) write(nameMap map[string]string, b *orm.PlainSqlBuilder) {
	b.Repeat(len(o.items), b.SepFix(" ORDER BY ", ", ", "", false), nil, func(_, i int) {
		item := o.items[i]
		b.Write(mapColumn(nameMap, item.column)).Write(" ")
		b.Write(item.seq.sql)
	})
}

type Paging struct {
	offset, pageSize int
}

func Order() *OrderBy {
	return &OrderBy{}
}

func Page(offset, pageSize int) *Paging {
	return &Paging{offset: offset, pageSize: pageSize}
}

func And() *CondGroup {
	return &CondGroup{or: false}
}

func Or() *CondGroup {
	return &CondGroup{or: true}
}

func Not() not {
	return not{}
}

//=============================================================
//=========================== Eums ============================
//=============================================================

type orderBySeq struct {
	e.EnumElem
	sql string
}

type _orderBySeq struct {
	e.Enum[orderBySeq]
	asc,
	desc orderBySeq
}

var orderBySeq_ = e.NewEnum(_orderBySeq{
	asc:  orderBySeq{sql: "ASC"},
	desc: orderBySeq{sql: "DESC"},
})

type orderByItem struct {
	column string
	seq    orderBySeq
}

//=============================================================
//========================== Others ===========================
//=============================================================

func mapColumns(nameMap map[string]string, columns []string) []string {
	var target []string
	for _, column := range columns {
		if c, ok := nameMap[column]; ok {
			column = c
		}
		target = append(target, column)
	}
	return target
}

func mapColumn(nameMap map[string]string, column string) string {
	if c, ok := nameMap[column]; ok {
		column = c
	}
	return column
}

func mergeColumns(columns ...[]string) []string {
	l := 0
	for _, e := range columns {
		l += len(e)
	}
	result := make([]string, 0, l)
	for _, a := range columns {
		result = append(result, a...)
	}
	return result
}
